### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by LeoF9** [Martinii89/BallchasingReplayPlayer#1]
The plugin is not working anymore after RL update (bm up to date as well). On ballchasing the arrow to play the replay no longer shows up and the plugin does not show up in game in the bm plugins tab. 

Is it incompatible with the replay review plugin somehow? I recently installed that but I dont see why it would cause issues. Not sure how to troubleshoot this.

**Comment by LeoF9** [comment]
(ive tried reinstalling it but thats about it)

**Comment by Martinii89** [comment]
It's broken after the last bm update. I have a new working branch ready. It should be pushed to the site shortly.

**Comment by LeoF9** [comment]
Great thanks so much. Just wanted to make sure it wasnt on my end. Take your time.

**Comment by daflamingpotato** [comment]
Hi, just curious if an update is still in work? The plugin is not working for me

**Comment by shuja-u** [comment]
Not working for me either. No new button shows up on ballchasing in Firefox and also in Edge. Is there a specific browser that needs to be used?

**Comment by Martinii89** [comment]
I just tested it today (18.05.2023). As of today it's still working with Chrome. If you still have issues it may be your browser rejecting the websocket connection to localhost (the plugin). If you still think the plugin is broken I need more info
