### ISSUE TITLE
Opening up a 2nd instance of RL on second monitor

### ISSUE THREAD

**Issue by hutchy81** [Martinii89/BallchasingReplayPlayer#3]
Have been using this plugin ever since it came out, and has been working fine. Recently when I click play on Ballchasing, instead of it opening the replay on my already open Rocket league on my main display, it will open up another instance of Rocket league on my 2nd monitor and play the correct replay, and within a few seconds the original instance crashes out, leaving an the 2nd instance running and unable to move it back to my main screen.

**Comment by Martinii89** [comment]
There is no way this plugin will start up a new instance of the game. It doesn't interact with windows, steam or epic games launcher in any way. I'm thinking you must have installed something else that's somehow hijack the same mechanism (a websocket connection to the running game) for it's own purposes

**Comment by hutchy81** [comment]
Ok, I understand, I've recorded a video and uploaded to youtube [here](https://youtu.be/7JlOe0xDH4E). I used a webcam so you can see what's happening when alt tabbing as the display recordings go black.

It maybe that a second instance isn't opening, but it is moving RL over to my 2nd screen, is there anything that can be done to prevent this. (it can be corrected by going to windowed mode then back to fullscreen, but don't want to have to do this everytime!)

**Comment by Martinii89** [comment]
Almost looks like the function that tries to make the game the active window is activating\moving it to the second monitor.. Did you move the game to your secondary monitor after starting it or something? Never seen that happen before. My best suggestion would be to try to put the game in windowed or borderles fullscreen mode while using the plugin.

**Comment by hutchy81** [comment]
No, I always start on that monitor. what's weird is that i have had this setup for a few years, and the replay loader has been fine up until recently. I guess there's nothing in the code for the plugin to change this :(

**Comment by Martinii89** [comment]
I will push a update with a setting to toggle on\off the "bring the game to the front" feature

**Comment by Martinii89** [comment]
Update pending review on bakkesplugin now. Should be out soon-ish
