### ISSUE TITLE
Not working. What should change?

### ISSUE THREAD

**Issue by johanwintgens** [Martinii89/BallchasingReplayPlayer#7]
Hey @Martinii89, so the plugin is showing in BakkesMod, but ballchasing.com does not show the Play button.

Since it looks like this plugin is abandoned, I'm willing to have a crack at it and open a PR, even though my knowledge of C++ is limited. Do you have any idea what might be causing the issue and how I might be able to solve it?

**Comment by Martinii89** [comment]
I just tested it today (18.05.2023). As of today it's still working with Chrome. If you still have issues it may be your browser rejecting the websocket connection to localhost (the plugin). If you still think the plugin is broken I need more info
